### ISSUE TITLE
RuntimeError: Tensors of type TensorImpl do not have sizes

### ISSUE THREAD

**Issue by chengqi0514** [Gorilla-Lab-SCUT/Fantasia3D#15]
Hi, I get this problem when i run the code:
Loading extension module renderutils_plugin...
  0%|                                                                                                                                             | 0/3001 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 649, in <module>
    geometry, mat = optimize_mesh(glctx, geometry, mat, lgt, dataset_train, dataset_validate, 
  File "train.py", line 380, in optimize_mesh
    result_image, result_dict = validate_itr(glctx, prepare_batch(next(v_it), FLAGS.train_background), geometry, opt_material, lgt, FLAGS)  #prepare_batch(next(v_it), FLAGS.background)
  File "train.py", line 177, in validate_itr
    buffers = geometry.render(glctx, target, lgt, opt_material)
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/geometry/dmtet.py", line 213, in render
    return render.render_mesh(glctx, 
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/render/render.py", line 248, in render_mesh
    v_pos_clip = ru.xfm_points(mesh.v_pos[None, ...], mtx_in)
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/render/renderutils/ops.py", line 527, in xfm_points
    out = _xfm_func.apply(points, matrix, True)
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/render/renderutils/ops.py", line 508, in forward
    return _get_plugin().xfm_fwd(points, matrix, isPoints, False)
RuntimeError: Tensors of type TensorImpl do not have sizes

**Comment by ARuiChen** [comment]
Hi, could you provide the version of the package? (pip list)

**Comment by chengqi0514** [comment]
> Hi, could you provide the version of the package? (pip list)

Hi, I have fixed the problem.

**Comment by ARuiChen** [comment]
Glad to hear this!
