### ISSUE TITLE
TypeError: tick() takes 9 positional arguments but 10 were given

### ISSUE THREAD

**Issue by chengqi0514** [Gorilla-Lab-SCUT/Fantasia3D#16]
Hi, I got a bug when I run appearance_modeling:
Loading extension module renderutils_plugin...
[INFO] loading stable diffusion...
[INFO] loaded stable diffusion!
Base mesh has 65882 triangles and 33000 vertices.
  0%|                                                                                                                                  | 0/2001 [01:09<?, ?it/s]
Traceback (most recent call last):
  File "/remote-home/hbyang/anaconda3/envs/general/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/remote-home/hbyang/anaconda3/envs/general/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/remote-home/hbyang/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/train.py", line 682, in <module>
    geometry, mat = optimize_mesh(glctx, geometry, mat, lgt, dataset_train, dataset_validate, FLAGS, 
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/train.py", line 417, in optimize_mesh
    sds_loss,img_loss, reg_loss = model(target, it, if_nomral, if_pretain= if_pretain, scene_and_vertices =None)
  File "/remote-home/hbyang/anaconda3/envs/general/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/remote-home/hbyang/codes/text-to-3d/Fantasia3D/train.py", line 310, in forward
    return self.geometry.tick(glctx, target, self.light, self.material, it , if_nomral, self.guidance, self.FLAGS.mode, self.if_flip_the_normal)
TypeError: tick() takes 9 positional arguments but 10 were given

And I found the bug caused by 
https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/3db20e336808428d99f439fbb8d36eda9b808ccc/train.py#L678，
DLMesh.tick doesnt have 'if_flip_the_normal' argument.

**Comment by ARuiChen** [comment]
Be fixed.

**Comment by yoxu515** [comment]
Hi, could you please have a look on this issue again? I found this error still exists.
In train.py Line310, the tick accepts 9 arguments, but the definition in dlmesh.py Line 83 still has 8 arguments. (self is not counted here)
The error occurs when running
```
python3  train.py --config configs/pineapple_appearance_strategy0_single_gpu.json
```
Before it, the geometry has been generated by
```
python3  train.py --config configs/pineapple_geometry_single_gpu.json
```

**Comment by ARuiChen** [comment]
Hi, @yoxu515 Did you pull the latest commit? Could you print the log?

**Comment by yoxu515** [comment]
Thank you for your reminder, I have pulled the latest commit and I noticed the bug has been fixed.
