### ISSUE TITLE
Problem installing on Ubuntu?

### ISSUE THREAD

**Issue by Thundros** [Gorilla-Lab-SCUT/Fantasia3D#21]
Hi @ARuiChen! I had an issue installing this on my Ubuntu. 

Here's my log : 

~/Fantasia3D$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/NVlabs/nvdiffrast.git (from -r requirements.txt (line 9))
  Cloning https://github.com/NVlabs/nvdiffrast.git to /tmp/pip-req-build-cqpmcxi8
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast.git /tmp/pip-req-build-cqpmcxi8
  Resolved https://github.com/NVlabs/nvdiffrast.git to commit 335cfa6b33d785730a04283994214bed57884e87
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch (from -r requirements.txt (line 10))
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-rgk405vw
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-rgk405vw
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 1ee07877239b46fbdafeb8ae155a786a84a37e18
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-rgk405vw/bindings/torch/setup.py", line 49, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      Building PyTorch extension for tiny-cuda-nn version 1.7
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ARuiChen** [comment]
Hi, it seems that the error appeared when installing the tiny-cuda-nn.
You can try another way to install it :
```python
git clone https://github.com/NVlabs/tiny-cuda-nn.git
cd tiny-cuda-nn
cd bindings/torch
python setup.py install
```

**Comment by Thundros** [comment]
@ARuiChen : 

python3 setup.py install
Building PyTorch extension for tiny-cuda-nn version 1.7
Traceback (most recent call last):
  File "/root/Fantasia3D/tiny-cuda-nn/bindings/torch/setup.py", line 49, in <module>
    raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.

EDIT: Using the latest Ubuntu in VMWare Workstation 16 Pro

**Comment by Thundros** [comment]
@ARuiChen ???

**Comment by bennyguo** [comment]
@Thundros Please be patient. This is an open-source project, the maintainer has no obligation to answer every question on time.

**Comment by ARuiChen** [comment]
Hi, @Thundros ! See [here](https://github.com/nerfstudio-project/nerfstudio/issues/980) 
Please be patient. It is difficult for me to answer every question on time.

**Comment by Thundros** [comment]
Hi, @ARuiChen! I have another error apparently, here is my log : 

kaorixvii@kaorixvii-virtual-machine:~/Fantasia3D$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/NVlabs/nvdiffrast.git (from -r requirements.txt (line 9))
  Cloning https://github.com/NVlabs/nvdiffrast.git to /tmp/pip-req-build-476by8_0
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast.git /tmp/pip-req-build-476by8_0
  Resolved https://github.com/NVlabs/nvdiffrast.git to commit 335cfa6b33d785730a04283994214bed57884e87
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch (from -r requirements.txt (line 10))
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-75fv5_g7
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-75fv5_g7
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 1ee07877239b46fbdafeb8ae155a786a84a37e18
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-75fv5_g7/bindings/torch/setup.py", line 8, in <module>
          import torch
        File "/home/kaorixvii/.local/lib/python3.10/site-packages/torch/__init__.py", line 228, in <module>
          _load_global_deps()
        File "/home/kaorixvii/.local/lib/python3.10/site-packages/torch/__init__.py", line 187, in _load_global_deps
          raise err
        File "/home/kaorixvii/.local/lib/python3.10/site-packages/torch/__init__.py", line 168, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/kaorixvii/.local/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
kaorixvii@kaorixvii-virtual-machine:~/Fantasia3D$ ^C

**Comment by ARuiChen** [comment]
@Thundros Could you print the result of "pip list" in your command line?

**Comment by Thundros** [comment]
yes, @ARuiChen, here it is : 

kaorixvii@kaorixvii-virtual-machine:~/Fantasia3D$ pip list
Package                 Version
----------------------- -------------
apturl                  0.5.2
bcrypt                  3.2.0
blinker                 1.4
Brlapi                  0.8.3
certifi                 2020.6.20
chardet                 4.0.0
click                   8.0.3
cmake                   3.25.0
colorama                0.4.4
command-not-found       0.3
cryptography            3.4.8
cupshelpers             1.0
dbus-python             1.2.18
defer                   1.0.6
distro                  1.7.0
distro-info             1.1build1
duplicity               0.8.21
fasteners               0.14.1
filelock                3.9.0
future                  0.18.2
httplib2                0.20.2
idna                    3.3
importlib-metadata      4.6.4
jeepney                 0.7.1
Jinja2                  3.1.2
keyring                 23.5.0
language-selector       0.1
launchpadlib            1.10.16
lazr.restfulclient      0.14.4
lazr.uri                1.0.6
lit                     15.0.7
lockfile                0.12.2
louis                   3.20.0
macaroonbakery          1.3.1
Mako                    1.1.3
MarkupSafe              2.0.1
monotonic               1.6
more-itertools          8.10.0
mpmath                  1.2.1
netifaces               0.11.0
networkx                3.0
numpy                   1.25.0
oauthlib                3.2.0
olefile                 0.46
paramiko                2.9.3
pexpect                 4.8.0
Pillow                  9.0.1
pip                     22.0.2
protobuf                3.12.4
ptyprocess              0.7.0
pycairo                 1.20.1
pycups                  2.0.1
PyGObject               3.42.1
PyJWT                   2.3.0
pymacaroons             0.13.0
PyNaCl                  1.5.0
pyparsing               2.4.7
pyRFC3339               1.1
python-apt              2.4.0+ubuntu1
python-dateutil         2.8.1
python-debian           0.1.43ubuntu1
pytz                    2022.1
pyxdg                   0.27
PyYAML                  5.4.1
reportlab               3.6.8
requests                2.25.1
screen-resolution-extra 0.0.0
SecretStorage           3.3.1
setuptools              59.6.0
six                     1.16.0
sympy                   1.11.1
systemd-python          234
torch                   1.12.1+cu113
torchvision             0.13.1+cu113
triton                  2.0.0
typing_extensions       4.6.3
ubuntu-advantage-tools  8001
ubuntu-drivers-common   0.0.0
ufw                     0.36.1
unattended-upgrades     0.1
urllib3                 1.26.5
usb-creator             0.3.7
wadllib                 1.3.6
wheel                   0.37.1
xdg                     5
xkit                    0.0.0
zipp                    1.0.0
kaorixvii@kaorixvii-virtual-machine:~/Fantasia3D$ ^C

**Comment by ARuiChen** [comment]
Search information about "libtorch_global_deps.so: cannot open shared object file: No such file or directory" in  Google.
If you still can't solve it, I will upload a docker file this week. Please be patient.

**Comment by Thundros** [comment]
@ARuiChen No luck... Didn't work.

**Comment by Thundros** [comment]
@ARuiChen Thank you for the docker in advance!

**Comment by ARuiChen** [comment]
@Thundros Done!

**Comment by Dennisboyangzhang** [comment]
Thanks @ARuiChen 

I tried the image and run to following errors. I'm looking at it.  I would appreciate If someone drop a hint

`  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_052caec9d5bceeb59b9a13cb3338ce64d.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_06b6dd3317cd1748fb948900df8beec57.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_078e1f4b2964afcce5387420c9c8eaea8.html: Filename too long
  error: unable to create file docs/structcutlass_1_1transform_1_1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_0bc37beaa523707a55987f4ffcc372fcd.html: Filename too long
  error: unable to create file examples/29_ampere_3xtf32_fast_accurate_tensorop_complex_gemm/29_ampere_3xtf32_fast_accurate_tensorop_complex_gemm.cu: Filename too long
  fatal: Unable to checkout '319a389f42b776fae5701afcb943fc03be5b5c25' in submodule path 'third_party/flash-attention/csrc/flash_attn/cutlass'
  fatal: Failed to recurse into submodule path 'third_party/flash-attention'
  error: subprocess-exited-with-error`

**Comment by zxhxixi** [comment]
it has issures with the version of open3d ....?

Could not find a version that satisfies the requirement open3d==0.14.1 (from versions: 0.16.0, 0.17.0)
No matching distribution found for open3d==0.14.1

**Comment by Thundros** [comment]
@ARuiChen : How do I create the JSON file needed for Google Colab?

**Comment by ARuiChen** [comment]
Sorry for the late reply! @zxhxixi You should use the Python version from 3.6 to 3.9 to install the open3d==0.14.1.

**Comment by ARuiChen** [comment]
@Thundros Just copy a new Json file from the template and rename it.
