### ISSUE TITLE
Problem appearance_modeling

### ISSUE THREAD

**Issue by xiexueshuang** [Gorilla-Lab-SCUT/Fantasia3D#24]
Hi @ARuiChen! 
I encountered a problem when running the following command：

`python3 -m torch.distributed.launch --nproc_per_node=8 train.py --config configs/Gundam_appearance.json`

Here's my log :

Traceback (most recent call last):
  File "train.py", line 603, in <module>
    lgt = light.load_env(FLAGS.envmap, scale=FLAGS.env_scale)
  File "/data0/xxl/Fantasia3D/render/light.py", line 146, in load_env
    return _load_env_hdr(fn, scale)
  File "/data0/xxl/Fantasia3D/render/light.py", line 135, in _load_env_hdr
    latlong_img = torch.tensor(util.load_image(fn), dtype=torch.float32, device='cuda')*scale
  File "/data0/xxl/Fantasia3D/render/util.py", line 423, in load_image
    img = load_image_raw(fn)
  File "/data0/xxl/Fantasia3D/render/util.py", line 420, in load_image_raw
    return imageio.imread(fn)
  File "/home/amax/.local/lib/python3.8/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/amax/.local/lib/python3.8/site-packages/imageio/core/functions.py", line 181, in get_reader
    raise ValueError(
ValueError: Could not find a format to read the specified file in single-image mode

**Comment by shengyu-meng** [comment]
This because naive imageio can not read the HDR file.
run `imageio_download_bin freeimage` in terminal to install the extension will slove it.
