### ISSUE TITLE
Docker image launching issue

### ISSUE THREAD

**Issue by ShudaLi** [Gorilla-Lab-SCUT/Fantasia3D#27]
Hey Rui! Great work and thanks a lot for sharing it! 

I encounter this issue when launching multi-gpu (2 x A100-81G). I'm using two GPU instead of 8 because I reckon there's sufficient GRAM (2 x 81G > 8 x 24G)  Any idea what is the problem? Many thanks in advance?   

the docker container is launched with the command:

$sudo docker container run --gpus '"device=2,3"' --ipc=host -e PYTHONUNBUFFERED=1 -v /data2/shuda/Fantasia3D:/workspace/Fantasia3D -it registry.cn-guangzhou.aliyuncs.com/baopin/fantasia3d:1.0 

where the Fantasia3D repo is at /data2/shuda/Fantasia3D

root@cdde8ed9639c:/workspace/Fantasia3D# python3 -m torch.distributed.launch --nproc_per_node=2 train.py --config configs/car_geometry.json
/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/workspace/Fantasia3D/train.py", line 25, in <module>
    from geometry.dmtet import DMTetGeometry
  File "/workspace/Fantasia3D/geometry/dmtet.py", line 17, in <module>
    from geometry.dmtet_network import Decoder
  File "/workspace/Fantasia3D/geometry/dmtet_network.py", line 3, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.9/dist-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.9/dist-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 35, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 80.
Traceback (most recent call last):
  File "/workspace/Fantasia3D/train.py", line 25, in <module>
    from geometry.dmtet import DMTetGeometry
  File "/workspace/Fantasia3D/geometry/dmtet.py", line 17, in <module>
    from geometry.dmtet_network import Decoder
  File "/workspace/Fantasia3D/geometry/dmtet_network.py", line 3, in <module>
    import tinycudann as tcnn
  File "/usr/local/lib/python3.9/dist-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/usr/local/lib/python3.9/dist-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 35, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 80.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 81) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-04_02:27:06
  host      : cdde8ed9639c
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 82)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-04_02:27:06
  host      : cdde8ed9639c
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 81)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ShudaLi** [comment]
figured out the above problem has nothing to do with multi-gpu training.  It's because unable to locate the dependencies.

**Comment by ShudaLi** [comment]
Bypass the above error by reinstalling the requirements inside the docker container. The docker container should work fine, perhaps an instruction on how to launch the container will avoid other running into the same problem.

**Comment by ShudaLi** [comment]
As the problem solved I close the issue.

**Comment by ARuiChen** [comment]
Glad to hear that!
